//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Park_Play
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parks
    {
        public int Id { get; set; }
        public string ParkName { get; set; }
        public string streetAddress { get; set; }
        public string city { get; set; }
        public string stateCode { get; set; }
        public int zipcode { get; set; }
        public double ContactNumber { get; set; }
        public float lat { get; set; }
        public float lng { get; set; }
    }
}
